# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "production-aws-use1-s3-tf-state"
    dynamodb_table = "production-aws-use1-ddb-tf-state-lock"
    encrypt        = true
    key            = "homelab/production/homelab/argocd/terraform.tfstate"
    region         = "us-east-1"
  }
}
