apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: longhorn-system

commonLabels:
  pod-security.kubernetes.io/enforce: privileged

patchesStrategicMerge:
- init-container-patch.yaml