---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
      - name: homer
        imagePullPolicy: Always
        image: b4bz/homer
        ports:
        - containerPort: 8080