{{- range .Values.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .pvc.size }}
  storageClassName: {{ .pvc.storageClassName }}
{{ end }}
