---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{ .Values.controller.namespace }}"
  name: kopfexample-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "{{ .Values.controller.namespace }}"
  name: configmap-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Values.controller.namespace }}"
  name: kopfexample-rolebinding-namespaced-configmap-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-manager
subjects:
  - kind: ServiceAccount
    namespace: "{{ .Values.controller.namespace }}"
    name: kopfexample-account