apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-lb-iprange
  namespace: metallb-system
spec:
  addresses:
  - 10.1.0.192/26
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system