apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-role.yml
  - cluster-role-binding.yml
  - service-account.yml
  - deployment.yml

labels:
- pairs:
    app: traefik
  includeSelectors: true